name: Jonathan Lima - Designer de Interfaces
description: Designer de Interfaces
meta_description: "Designer de interfaces em recife, Designer de Interação em Recife"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'jonathanslima.github.io'
google_analytics: 'UA-66392540-1'
disqus: true
disqus_shortname: 'jonathanslima'

# Details for the RSS feed generator
url:            'http://jonathanslima.github.io/'
author:         'Jonathan'
authorTwitter:  'jonathan_slima'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
