name: Jonathan Lima - Desenvolvedor Front End
description: Desenvolvedor Front End
meta_description: "Desenvolvedor Front end em recife, redesign e desenvolvimento de sites"

aboutPage: true

markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate]
paginate: 5

baseurl: /
domain_name: 'jonathanslima.github.io'
google_analytics: 'UA-66392540-1'
disqus: true
disqus_shortname: 'jonathanslima'
nofollow: 'rel="nofollow"'
exclude:
  - package.json
  - node_modules
  - gulpfile.js

# Details for the RSS feed generator
url:            'http://jonathanslima.github.io/'
author:         'Jonathan Lima'
authorTwitter:  'jonathan_slima'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
