# Site settings
title: Jonathan Lima
header-img: img/home-bg.jpg
email: jonathan633.jl@gmail.com
description: "Blog sobre desenvolvimento front end e design de interfaces"
baseurl: ""
url: "http://jonathan_slima.com"
twitter_username: jonathan_slima
github_username:  jonathanslima
facebook_username:  jonathansilva.86

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
